// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskControlBackend.Data;

#nullable disable

namespace TaskControlBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251123214055_InitialWithDelegation")]
    partial class InitialWithDelegation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskControlBackend.Models.Capacidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Capacidades", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.Chat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.ChatMember", b =>
                {
                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Role")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("ChatId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMembers");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("ChatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SenderId");

                    b.HasIndex("ChatId", "CreatedAt");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AsignadoAUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("DelegacionAceptada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DelegacionResueltaAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DelegadaAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DelegadoAUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DelegadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Departamento")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaDelegada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciaImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaTexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinalizadaAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoRechazoJefe")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAUsuarioId");

                    b.HasIndex("CreatedByUsuarioId");

                    b.HasIndex("DelegadoPorUsuarioId");

                    b.HasIndex("DelegadoAUsuarioId", "EstaDelegada");

                    b.HasIndex("EmpresaId", "Estado");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaCapacidadRequerida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TareaId", "Nombre")
                        .IsUnique();

                    b.ToTable("TareasCapacidadesRequeridas", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Departamento")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("NivelHabilidad")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.UsuarioCapacidad", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapacidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("UsuarioId", "CapacidadId");

                    b.HasIndex("CapacidadId");

                    b.ToTable("UsuarioCapacidades", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.Capacidad", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.Chat", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.ChatMember", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Chat.Chat", "Chat")
                        .WithMany("Members")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.Message", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Chat.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Usuario", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TaskControlBackend.Models.RefreshToken", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Tarea", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "AsignadoAUsuario")
                        .WithMany()
                        .HasForeignKey("AsignadoAUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskControlBackend.Models.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedByUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Usuario", "DelegadoAUsuario")
                        .WithMany()
                        .HasForeignKey("DelegadoAUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskControlBackend.Models.Usuario", "DelegadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("DelegadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskControlBackend.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignadoAUsuario");

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DelegadoAUsuario");

                    b.Navigation("DelegadoPorUsuario");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaCapacidadRequerida", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Tarea", "Tarea")
                        .WithMany("CapacidadesRequeridas")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Usuario", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("TaskControlBackend.Models.UsuarioCapacidad", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Capacidad", "Capacidad")
                        .WithMany("UsuarioCapacidades")
                        .HasForeignKey("CapacidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Usuario", "Usuario")
                        .WithMany("UsuarioCapacidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Capacidad", b =>
                {
                    b.Navigation("UsuarioCapacidades");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.Chat", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Tarea", b =>
                {
                    b.Navigation("CapacidadesRequeridas");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioCapacidades");
                });
#pragma warning restore 612, 618
        }
    }
}
