// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskControlBackend.Data;

#nullable disable

namespace TaskControlBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251201021152_AddBlobStorageSupport")]
    partial class AddBlobStorageSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskControlBackend.Models.Capacidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nombre")
                        .IsUnique();

                    b.ToTable("Capacidades", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentType")
                        .HasColumnType("int");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("EditedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FileMimeType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("FileSizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("FileUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEdited")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("ReplyToMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SenderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReplyToMessageId")
                        .HasDatabaseName("IX_ChatMessage_ReplyToMessageId");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("IX_ChatMessage_SenderId");

                    b.HasIndex("ConversationId", "SentAt")
                        .HasDatabaseName("IX_ChatMessage_ConversationId_SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("LastActivityAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LastActivityAt")
                        .HasDatabaseName("IX_Conversation_LastActivityAt");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.ConversationMember", b =>
                {
                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMuted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset>("JoinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("LastReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("ConversationId", "UserId");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_ConversationMember_UserId");

                    b.HasIndex("UserId", "IsActive")
                        .HasDatabaseName("IX_ConversationMember_UserId_IsActive");

                    b.ToTable("ConversationMembers");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.MessageDeliveryStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DeliveredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DeliveredToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DeliveredToUserId")
                        .HasDatabaseName("IX_MessageDeliveryStatus_UserId");

                    b.HasIndex("MessageId", "DeliveredToUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MessageDeliveryStatus_MessageId_UserId_Unique");

                    b.ToTable("MessageDeliveryStatuses");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.MessageReadStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ReadAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("ReadByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ReadByUserId")
                        .HasDatabaseName("IX_MessageReadStatus_UserId");

                    b.HasIndex("MessageId", "ReadByUserId")
                        .IsUnique()
                        .HasDatabaseName("IX_MessageReadStatus_MessageId_UserId_Unique");

                    b.ToTable("MessageReadStatuses");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Estado");

                    b.ToTable("Empresas", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRevoked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("RevokeReason")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId", "TokenHash")
                        .IsUnique();

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AsignadoAUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("CreatedByUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool?>("DelegacionAceptada")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DelegacionResueltaAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DelegadaAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DelegadoAUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DelegadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Departamento")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstaDelegada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciaImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaTexto")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FinalizadaAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MotivoCancelacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoRechazoJefe")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAUsuarioId");

                    b.HasIndex("CreatedByUsuarioId");

                    b.HasIndex("DelegadoPorUsuarioId");

                    b.HasIndex("DelegadoAUsuarioId", "EstaDelegada");

                    b.HasIndex("EmpresaId", "Estado");

                    b.ToTable("Tareas", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaAsignacionHistorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AsignadoAUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AsignadoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TipoAsignacion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AsignadoAUsuarioId");

                    b.HasIndex("AsignadoPorUsuarioId");

                    b.HasIndex("TareaId");

                    b.ToTable("TareasAsignacionesHistorial");
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaCapacidadRequerida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TareaId", "Nombre")
                        .IsUnique();

                    b.ToTable("TareasCapacidadesRequeridas", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaDocumentoAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchivoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubidoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoMime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubidoPorUsuarioId");

                    b.HasIndex("TareaId")
                        .HasDatabaseName("IX_TareaDocumentoAdjunto_TareaId");

                    b.ToTable("TareasDocumentosAdjuntos");
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaEvidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ArchivoUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SubidoPorUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint");

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TipoMime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SubidoPorUsuarioId");

                    b.HasIndex("TareaId")
                        .HasDatabaseName("IX_TareaEvidencia_TareaId");

                    b.ToTable("TareasEvidencias");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Departamento")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FotoPerfilUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("NivelHabilidad")
                        .HasColumnType("int");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaId");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.UsuarioCapacidad", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CapacidadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Nivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("UsuarioId", "CapacidadId");

                    b.HasIndex("CapacidadId");

                    b.ToTable("UsuarioCapacidades", (string)null);
                });

            modelBuilder.Entity("TaskControlBackend.Models.Capacidad", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.ChatMessage", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Chat.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Chat.ChatMessage", "ReplyToMessage")
                        .WithMany("Replies")
                        .HasForeignKey("ReplyToMessageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskControlBackend.Models.Usuario", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("ReplyToMessage");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.Conversation", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.ConversationMember", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Chat.Conversation", "Conversation")
                        .WithMany("Members")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Usuario", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.MessageDeliveryStatus", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "DeliveredToUser")
                        .WithMany()
                        .HasForeignKey("DeliveredToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Chat.ChatMessage", "Message")
                        .WithMany("DeliveryStatuses")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveredToUser");

                    b.Navigation("Message");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.MessageReadStatus", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Chat.ChatMessage", "Message")
                        .WithMany("ReadStatuses")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Usuario", "ReadByUser")
                        .WithMany()
                        .HasForeignKey("ReadByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("ReadByUser");
                });

            modelBuilder.Entity("TaskControlBackend.Models.RefreshToken", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "Usuario")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Tarea", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "AsignadoAUsuario")
                        .WithMany()
                        .HasForeignKey("AsignadoAUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskControlBackend.Models.Usuario", "CreatedByUsuario")
                        .WithMany()
                        .HasForeignKey("CreatedByUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Usuario", "DelegadoAUsuario")
                        .WithMany()
                        .HasForeignKey("DelegadoAUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskControlBackend.Models.Usuario", "DelegadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("DelegadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaskControlBackend.Models.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignadoAUsuario");

                    b.Navigation("CreatedByUsuario");

                    b.Navigation("DelegadoAUsuario");

                    b.Navigation("DelegadoPorUsuario");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaAsignacionHistorial", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "AsignadoAUsuario")
                        .WithMany()
                        .HasForeignKey("AsignadoAUsuarioId");

                    b.HasOne("TaskControlBackend.Models.Usuario", "AsignadoPorUsuario")
                        .WithMany()
                        .HasForeignKey("AsignadoPorUsuarioId");

                    b.HasOne("TaskControlBackend.Models.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AsignadoAUsuario");

                    b.Navigation("AsignadoPorUsuario");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaCapacidadRequerida", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Tarea", "Tarea")
                        .WithMany("CapacidadesRequeridas")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaDocumentoAdjunto", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "SubidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("SubidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Tarea", "Tarea")
                        .WithMany("DocumentosAdjuntos")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubidoPorUsuario");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("TaskControlBackend.Models.TareaEvidencia", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Usuario", "SubidoPorUsuario")
                        .WithMany()
                        .HasForeignKey("SubidoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Tarea", "Tarea")
                        .WithMany("Evidencias")
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubidoPorUsuario");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Usuario", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("TaskControlBackend.Models.UsuarioCapacidad", b =>
                {
                    b.HasOne("TaskControlBackend.Models.Capacidad", "Capacidad")
                        .WithMany("UsuarioCapacidades")
                        .HasForeignKey("CapacidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskControlBackend.Models.Usuario", "Usuario")
                        .WithMany("UsuarioCapacidades")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capacidad");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Capacidad", b =>
                {
                    b.Navigation("UsuarioCapacidades");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.ChatMessage", b =>
                {
                    b.Navigation("DeliveryStatuses");

                    b.Navigation("ReadStatuses");

                    b.Navigation("Replies");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Chat.Conversation", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Messages");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Tarea", b =>
                {
                    b.Navigation("CapacidadesRequeridas");

                    b.Navigation("DocumentosAdjuntos");

                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("TaskControlBackend.Models.Usuario", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UsuarioCapacidades");
                });
#pragma warning restore 612, 618
        }
    }
}
